format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$env_var\
$sudo\
$cmd_duration\
$terraform\
$line_break\
$status\
$shell\
$character"""

add_newline = false

[line_break]
disabled = false

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "green"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"


[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "


[directory]
style = "blue"


[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
